### ISSUE TITLE
Configuration sharing across servers

### ISSUE THREAD

**Issue by fornex** [yuri-gushin/Roboo#6]
Hi,

I have following case:

Multiple domains on the same physical server are using Roboo.pm module. All domains have their own IP address and have a separate configuration file. Setting whitelist variable on one {server/location}, would automatically affect all other {servers/locations}. For example, setting whitelist UA('Googlebot') for domain x.com, would **sometimes** let Googlebot also on the domain y.com pass the Roboo verification, although, whitelist in y.com doesn't exist.

It looks like Roboo is using same shared memory for all domains to keep the configuration, or its a bug of nginx.

However, setting for each domain separate Roboo perl name (and package name), eliminates this behaviour. For example, for domain "x.com" we load Roboo module with the name **Roboo.x.com.pm** and for the domain "y.com", we load **Roboo.y.com.pm** - In this case everything works absolutelly perfect.

I'm using the latest version of Roboo

**Comment by yuri-gushin** [comment]
Hi,

Roboo itself only shares the "secret" in the Shared Memory - the rest of the configuration variables are actually handled by Nginx.

Your description along with my experience with Nginx and Perl shows that once the first call to "perl" is made from within Nginx - the perl module will run until Nginx stops/restarts/respawns, and that means that if the same perl module file/name is used, its running module will be re-used even if specified in different server/location blocks.  Since the same perl module is already running, it will have the configuration of the domain under which it was first loaded while serving possibly other domains - that explains why sometimes you saw this behavior, and sometimes you didn't.

Makes sense?

Looks like an issue with the way Nginx handles perl module execution across different blocks - appreciate you bringing it up! your solution can help others who are facing the same issue.
